#!/bin/bash

trap 'echo "Terminating..!"; exit 1' SIGINT

# https://stackoverflow.com/a/246128/2604915
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
BASE_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

SOURCE_DIR="$BASE_DIR/src"

# shellcheck source=src/parse_arguments.bash
source "$SOURCE_DIR/parse_arguments.bash"

# shellcheck source=src/virtualenv_setup.bash
source "$SOURCE_DIR/virtualenv_setup.bash"

# shellcheck source=src/delete_blobs.bash
source "$SOURCE_DIR/delete_blobs.bash"
